USERNAME: ''
PASSWORD: ''
URL_BASE: 'https://natal.rn.gov.br/sms/ponto/index.php'
URL_DATA: 'https://natal.rn.gov.br/sms/ponto/interno/aprova_justificativa/detalhes.php?'
PATH_FILE_BASE: r'C:\Users\paulo.morais\Desktop\BOT'